### ISSUE TITLE
Build failure on aarch64

### ISSUE THREAD

**Issue by akien-mga** [VirtualGL/virtualgl#91]
I'm updating Mageia 7's VirtualGL from 2.5.2 to 2.6.1, and it now fails to build on aarch64 (2.5.2 built fine):
```
cd /home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/build/util && /usr/bin/cc -DHAVE_DEVURANDOM -DSYSGLXHEADERS -DUSEXV -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D__APPNAME=\"VirtualGL\" -D__BITS=64 -D__BUILD=\"20190106\" -D__VERSION=\"2.6.1\" -I/home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/include -I/home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/build/include  -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -DNDEBUG -fPIC   -o CMakeFiles/vglutil.dir/pf.c.o   -c /home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/util/pf.c
In file included from /home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/util/pf.c:15:
/home/iurt/rpmbuild/BUILD/VirtualGL-2.6.1/include/boost/endian.hpp:121:3: error: #error The file boost/detail/endian.hpp needs to be set up for your CPU type.
 # error The file boost/detail/endian.hpp needs to be set up for your CPU type.
   ^~~~~
```

Full build log: 
[build.0.20190106081919.log.txt](https://github.com/VirtualGL/virtualgl/files/2730289/build.0.20190106081919.log.txt)

System:
Mageia 7, aarch64
GCC 8.2.1 (20181228)

**Comment by akien-mga** [comment]
That file was added in c8f92189, and seems to miss any reference to aarch64. It likely comes from an outdated boost version (the `endian.hpp` I have on system boost 1.68.0 is quite different, even with a completely different copyright header).
